// Generado desde src/data aprobado mediante scripts/u2-export-data.mjs.
namespace Mamporro.Core
{
    public static class Catalog
    {
        public static readonly WeaponDef[] Weapons=new WeaponDef[]{new WeaponDef{id="chancla",behavior="homing",values=new double[]{10,0.85,1,1,17,2.2,1,0.05,2,4},upgradable=new WStat[]{WStat.damage,WStat.cooldown,WStat.count,WStat.area,WStat.speed,WStat.pierce,WStat.critChance},hitFlash=1},new WeaponDef{id="naftalina",behavior="aura",values=new double[]{6,0.5,0,1,0,0,0,0.05,2,1.2},upgradable=new WStat[]{WStat.damage,WStat.cooldown,WStat.area,WStat.critChance,WStat.knockback},hitFlash=0.35},new WeaponDef{id="barra",behavior="arc",values=new double[]{16,1.2,1,1,0,0,0,0.08,2,7},upgradable=new WStat[]{WStat.damage,WStat.cooldown,WStat.count,WStat.area,WStat.critChance,WStat.knockback},hitFlash=1},new WeaponDef{id="dentaduras",behavior="orbit",values=new double[]{8,2.5,2,1,1,4,0,0.05,2,2.5},upgradable=new WStat[]{WStat.damage,WStat.cooldown,WStat.count,WStat.area,WStat.speed,WStat.duration,WStat.critChance},hitFlash=0.6},new WeaponDef{id="jersey",behavior="chain",values=new double[]{13,1.5,1,1,0,0,3,0.06,2.2,0.6},upgradable=new WStat[]{WStat.damage,WStat.cooldown,WStat.count,WStat.area,WStat.pierce,WStat.critChance},hitFlash=1},new WeaponDef{id="fregona",behavior="trail",values=new double[]{5,0.4,1,1,0,3,0,0.04,2,0},upgradable=new WStat[]{WStat.damage,WStat.cooldown,WStat.count,WStat.area,WStat.duration,WStat.critChance},hitFlash=0.35}};
        public static readonly TomeDef[] Tomes=new TomeDef[]{new TomeDef{id="damage",effects=new Effect[]{new Effect{stat=Stat.damage,amount=0.12,basis=false,integer=false,display="percent"}}},new TomeDef{id="attackSpeed",effects=new Effect[]{new Effect{stat=Stat.attackSpeed,amount=0.1,basis=false,integer=false,display="percent"}}},new TomeDef{id="projectiles",effects=new Effect[]{new Effect{stat=Stat.extraProjectiles,amount=1,basis=false,integer=true,display="number"}}},new TomeDef{id="area",effects=new Effect[]{new Effect{stat=Stat.area,amount=0.12,basis=false,integer=false,display="percent"}}},new TomeDef{id="moveSpeed",effects=new Effect[]{new Effect{stat=Stat.moveSpeed,amount=0.08,basis=false,integer=false,display="percent"}}},new TomeDef{id="vitality",effects=new Effect[]{new Effect{stat=Stat.maxHp,amount=20,basis=false,integer=true,display="number"},new Effect{stat=Stat.regen,amount=0.4,basis=false,integer=false,display="number"}}},new TomeDef{id="luck",effects=new Effect[]{new Effect{stat=Stat.luck,amount=10,basis=false,integer=true,display="number"}}},new TomeDef{id="magnet",effects=new Effect[]{new Effect{stat=Stat.pickupRadius,amount=0.25,basis=true,integer=false,display="percent"},new Effect{stat=Stat.xpGain,amount=0.08,basis=false,integer=false,display="percent"}}}};
        public static readonly ItemDef[] Items=new ItemDef[]{new ItemDef{id="gafas",rarity="common",effects=new Effect[]{new Effect{stat=Stat.critChance,amount=0.07,basis=false,integer=false,display="percent"}},maxStacks=0},new ItemDef{id="zapatillas",rarity="common",effects=new Effect[]{new Effect{stat=Stat.moveSpeed,amount=0.08,basis=false,integer=false,display="percent"}},maxStacks=0},new ItemDef{id="termo",rarity="common",effects=new Effect[]{new Effect{stat=Stat.attackSpeed,amount=0.08,basis=false,integer=false,display="percent"}},maxStacks=0},new ItemDef{id="cojin",rarity="common",effects=new Effect[]{new Effect{stat=Stat.armor,amount=4,basis=false,integer=true,display="number"}},maxStacks=0},new ItemDef{id="lupa",rarity="uncommon",effects=new Effect[]{new Effect{stat=Stat.critDamage,amount=0.25,basis=false,integer=false,display="percent"}},maxStacks=0},new ItemDef{id="loteria",rarity="uncommon",effects=new Effect[]{new Effect{stat=Stat.goldGain,amount=0.4,basis=false,integer=false,display="percent"}},maxStacks=0},new ItemDef{id="rulos",rarity="uncommon",effects=new Effect[]{new Effect{stat=Stat.luck,amount=15,basis=false,integer=true,display="number"}},maxStacks=0},new ItemDef{id="perlas",rarity="rare",effects=new Effect[]{},maxStacks=0},new ItemDef{id="monedero",rarity="rare",effects=new Effect[]{},maxStacks=0},new ItemDef{id="baraja",rarity="rare",effects=new Effect[]{new Effect{stat=Stat.choices,amount=1,basis=false,integer=true,display="number"}},maxStacks=1},new ItemDef{id="olla",rarity="epic",effects=new Effect[]{},maxStacks=0},new ItemDef{id="bata",rarity="legendary",effects=new Effect[]{},maxStacks=0}};
        public static readonly CharacterDef[] Characters=new CharacterDef[]{new CharacterDef{id="remedios",startingWeapon="chancla",maxHp=100,armor=0,pickupRadius=3.2,passive="slow",radius=3,amount=0.2,recharge=0},new CharacterDef{id="baguette",startingWeapon="barra",maxHp=100,armor=0,pickupRadius=3.2,passive="shield",radius=0,amount=0,recharge=8}};
        public static readonly EnemyDef[] Enemies=new EnemyDef[]{new EnemyDef{id="pelusa",behavior="chase",hp=14,speed=4.2,agility=5,damage=8,radius=0.5,height=0.95,xp=1,mass=1,goldChance=0.08,goldMin=1,goldMax=1,ranged=null,charge=null},new EnemyDef{id="cucaracha",behavior="chase",hp=7,speed=7.2,agility=9,damage=5,radius=0.42,height=0.5,xp=1,mass=0.7,goldChance=0.06,goldMin=1,goldMax=1,ranged=null,charge=null},new EnemyDef{id="taper",behavior="chase",hp=60,speed=2.6,agility=3,damage=14,radius=0.8,height=1,xp=4,mass=4,goldChance=0.35,goldMin=2,goldMax=4,ranged=null,charge=null},new EnemyDef{id="paloma",behavior="ranged",hp=12,speed=5,agility=6,damage=6,radius=0.45,height=0.8,xp=2,mass=0.8,goldChance=0.2,goldMin=1,goldMax=2,ranged=new RangedDef{preferred=10,range=16,cooldown=2.6,windup=0.5,projectileSpeed=11,projectileDamage=7,projectileRadius=0.3},charge=null},new EnemyDef{id="rata",behavior="charger",hp=420,speed=5.2,agility=5,damage=20,radius=0.9,height=1.5,xp=40,mass=6,goldChance=1,goldMin=20,goldMax=30,ranged=null,charge=new ChargeDef{cooldown=3.5,range=14,windup=0.8,dashTime=0.55,dashSpeed=19,damageMultiplier=1.5,recover=0.7}},new EnemyDef{id="pelusaMadre",behavior="boss",hp=3000,speed=3.4,agility=3,damage=25,radius=2.4,height=4.4,xp=0,mass=50,goldChance=0,goldMin=0,goldMax=0,ranged=null,charge=null}};
        public static readonly RarityDef[] Rarities=new RarityDef[]{new RarityDef{id="common",weight=60,luckBonus=0,power=1,min=1,max=2},new RarityDef{id="uncommon",weight=25,luckBonus=1.5,power=1.3,min=1,max=2},new RarityDef{id="rare",weight=10,luckBonus=3,power=1.65,min=2,max=2},new RarityDef{id="epic",weight=4,luckBonus=5,power=2.1,min=2,max=2},new RarityDef{id="legendary",weight=1,luckBonus=8,power=2.7,min=2,max=2}};
        public static readonly UpgradeStep[] Steps=new UpgradeStep[]{new UpgradeStep{amount=0.25,mode="mult",integer=false,max=double.PositiveInfinity},new UpgradeStep{amount=0.12,mode="rate",integer=false,max=3},new UpgradeStep{amount=1,mode="flat",integer=true,max=8},new UpgradeStep{amount=0.15,mode="mult",integer=false,max=2},new UpgradeStep{amount=0.15,mode="mult",integer=false,max=2},new UpgradeStep{amount=0.15,mode="mult",integer=false,max=2},new UpgradeStep{amount=1,mode="flat",integer=true,max=15},new UpgradeStep{amount=0.05,mode="flat",integer=false,max=double.PositiveInfinity},new UpgradeStep{amount=0.25,mode="flat",integer=false,max=double.PositiveInfinity},new UpgradeStep{amount=0.2,mode="mult",integer=false,max=3}};
    }
    public static class Tuning
    {
        public const double ReferenceMinutes=10;
        public const double SpawnHpGrowth=0.22;
        public const double SpawnHpCurve=0.02;
        public const double SpawnXpGrowth=0.12;
        public const double BossHpGrowth=0.2;
        public const double BossHpCurve=0.06;
        public const double FillerMinGold=10;
        public const double FillerChestFraction=0.5;
        public const double ChestBaseCost=15;
        public const double ChestCostStep=12;
        public const double ChestCostCurve=2.5;
        public const double FillerHeal=0.3;
        public const double InputGuard=0.4;
    }
}
